// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_expected_heterozygosity_cpp
arma::mat compute_expected_heterozygosity_cpp(const arma::mat& female_geno, const arma::mat& male_geno);
RcppExport SEXP _lagm_compute_expected_heterozygosity_cpp(SEXP female_genoSEXP, SEXP male_genoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type female_geno(female_genoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type male_geno(male_genoSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_expected_heterozygosity_cpp(female_geno, male_geno));
    return rcpp_result_gen;
END_RCPP
}
// compute_pair_gain_cpp
arma::mat compute_pair_gain_cpp(const arma::vec& female_ebv, const arma::vec& male_ebv);
RcppExport SEXP _lagm_compute_pair_gain_cpp(SEXP female_ebvSEXP, SEXP male_ebvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type female_ebv(female_ebvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type male_ebv(male_ebvSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pair_gain_cpp(female_ebv, male_ebv));
    return rcpp_result_gen;
END_RCPP
}
// compute_pair_relationship_diversity_cpp
arma::mat compute_pair_relationship_diversity_cpp(const arma::mat& relationship_matrix, const arma::uvec& female_index, const arma::uvec& male_index);
RcppExport SEXP _lagm_compute_pair_relationship_diversity_cpp(SEXP relationship_matrixSEXP, SEXP female_indexSEXP, SEXP male_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type relationship_matrix(relationship_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type female_index(female_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type male_index(male_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pair_relationship_diversity_cpp(relationship_matrix, female_index, male_index));
    return rcpp_result_gen;
END_RCPP
}
// lagm_score_grid_cpp
List lagm_score_grid_cpp(const arma::mat& female_geno, const arma::mat& male_geno, const arma::vec& female_ebv, const arma::vec& male_ebv);
RcppExport SEXP _lagm_lagm_score_grid_cpp(SEXP female_genoSEXP, SEXP male_genoSEXP, SEXP female_ebvSEXP, SEXP male_ebvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type female_geno(female_genoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type male_geno(male_genoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type female_ebv(female_ebvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type male_ebv(male_ebvSEXP);
    rcpp_result_gen = Rcpp::wrap(lagm_score_grid_cpp(female_geno, male_geno, female_ebv, male_ebv));
    return rcpp_result_gen;
END_RCPP
}
// lagm_relationship_score_grid_cpp
List lagm_relationship_score_grid_cpp(const arma::mat& relationship_matrix, const arma::uvec& female_index, const arma::uvec& male_index, const arma::vec& female_ebv, const arma::vec& male_ebv);
RcppExport SEXP _lagm_lagm_relationship_score_grid_cpp(SEXP relationship_matrixSEXP, SEXP female_indexSEXP, SEXP male_indexSEXP, SEXP female_ebvSEXP, SEXP male_ebvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type relationship_matrix(relationship_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type female_index(female_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type male_index(male_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type female_ebv(female_ebvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type male_ebv(male_ebvSEXP);
    rcpp_result_gen = Rcpp::wrap(lagm_relationship_score_grid_cpp(relationship_matrix, female_index, male_index, female_ebv, male_ebv));
    return rcpp_result_gen;
END_RCPP
}
// optimize_mating_plan_cpp
List optimize_mating_plan_cpp(const arma::mat& gain_mat, const arma::mat& div_mat, const IntegerVector& female_min, const IntegerVector& female_max, const IntegerVector& male_min, const IntegerVector& male_max, const int n_crosses, const int opt_mode, const double Gmin, const double Gmax, const double base_div, const double lookahead_t, const int n_iter, const double swap_prob, const double mutate_female_prob, const double init_prob, const double cooling_rate, const int stop_window, const double stop_eps, const int warmup_iter, const int n_pop, const int n_threads);
RcppExport SEXP _lagm_optimize_mating_plan_cpp(SEXP gain_matSEXP, SEXP div_matSEXP, SEXP female_minSEXP, SEXP female_maxSEXP, SEXP male_minSEXP, SEXP male_maxSEXP, SEXP n_crossesSEXP, SEXP opt_modeSEXP, SEXP GminSEXP, SEXP GmaxSEXP, SEXP base_divSEXP, SEXP lookahead_tSEXP, SEXP n_iterSEXP, SEXP swap_probSEXP, SEXP mutate_female_probSEXP, SEXP init_probSEXP, SEXP cooling_rateSEXP, SEXP stop_windowSEXP, SEXP stop_epsSEXP, SEXP warmup_iterSEXP, SEXP n_popSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gain_mat(gain_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type div_mat(div_matSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type female_min(female_minSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type female_max(female_maxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type male_min(male_minSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type male_max(male_maxSEXP);
    Rcpp::traits::input_parameter< const int >::type n_crosses(n_crossesSEXP);
    Rcpp::traits::input_parameter< const int >::type opt_mode(opt_modeSEXP);
    Rcpp::traits::input_parameter< const double >::type Gmin(GminSEXP);
    Rcpp::traits::input_parameter< const double >::type Gmax(GmaxSEXP);
    Rcpp::traits::input_parameter< const double >::type base_div(base_divSEXP);
    Rcpp::traits::input_parameter< const double >::type lookahead_t(lookahead_tSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type swap_prob(swap_probSEXP);
    Rcpp::traits::input_parameter< const double >::type mutate_female_prob(mutate_female_probSEXP);
    Rcpp::traits::input_parameter< const double >::type init_prob(init_probSEXP);
    Rcpp::traits::input_parameter< const double >::type cooling_rate(cooling_rateSEXP);
    Rcpp::traits::input_parameter< const int >::type stop_window(stop_windowSEXP);
    Rcpp::traits::input_parameter< const double >::type stop_eps(stop_epsSEXP);
    Rcpp::traits::input_parameter< const int >::type warmup_iter(warmup_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type n_pop(n_popSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_mating_plan_cpp(gain_mat, div_mat, female_min, female_max, male_min, male_max, n_crosses, opt_mode, Gmin, Gmax, base_div, lookahead_t, n_iter, swap_prob, mutate_female_prob, init_prob, cooling_rate, stop_window, stop_eps, warmup_iter, n_pop, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lagm_compute_expected_heterozygosity_cpp", (DL_FUNC) &_lagm_compute_expected_heterozygosity_cpp, 2},
    {"_lagm_compute_pair_gain_cpp", (DL_FUNC) &_lagm_compute_pair_gain_cpp, 2},
    {"_lagm_compute_pair_relationship_diversity_cpp", (DL_FUNC) &_lagm_compute_pair_relationship_diversity_cpp, 3},
    {"_lagm_lagm_score_grid_cpp", (DL_FUNC) &_lagm_lagm_score_grid_cpp, 4},
    {"_lagm_lagm_relationship_score_grid_cpp", (DL_FUNC) &_lagm_lagm_relationship_score_grid_cpp, 5},
    {"_lagm_optimize_mating_plan_cpp", (DL_FUNC) &_lagm_optimize_mating_plan_cpp, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_lagm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
